=== rconnolly2/Actividad3T_rconnolly/citas.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- TipoAutor -->
  <xs:simpleType name="TipoAutor">
    <xs:restriction base="xs:string">
      <xs:pattern value=".*examen.*"/> <!-- .* todos los caracteres es como any -->
    </xs:restriction>
  </xs:simpleType>

  <!-- TipoFecha -->
  <xs:simpleType name="TipoFecha">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{4} - [0-9]{4}" />
    </xs:restriction>
  </xs:simpleType>

  <!-- TipoCita -->
  <xs:complexType name="TipoCita">
    <xs:sequence>
        <xs:element name="autor" type="TipoAutor"/>
        <xs:element name="fechas" type="TipoFecha"/>
        <xs:element name="texto" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

<!-- Elemento RaÃ­z -->
  <xs:element name="citas">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="cita" minOccurs="3" maxOccurs="30" type="TipoCita"/>
        </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rconnolly2/Actividad3T_rconnolly/Citas.xml
<?xml version="1.0" encoding="UTF-8"?>
<citas
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
  xsi:noNamespaceSchemaLocation="citas.xsd">
  <cita>
    <autor>examenf</autor>
    <fechas>1879 - 1935</fechas>
    <texto>Todo ha cambiado. La gente se toma a los humoristas en serio y a los políticos en broma.</texto>
  </cita>
  <cita>
    <autor>Groucho Marx</autor>
    <fechas>1890 - 1977</fechas>
    <texto>No reírse de nada es de tontos, reírse de todo es de estúpidos.</texto>
  </cita>
  <cita>
    <autor>Isaac Asimov</autor>
    <fechas>1920 - 1992</fechas>
    <texto>La primera ley de la dietética parece ser: si está bueno, es malo para usted.</texto>
  </cita>
  <cita>
    <autor> El profesor </autor>
    <fechas>1952 - </fechas>
    <texto>La forma de empezar es dejar de hablar y empezar a hacer. </texto>
  </cita>
</citas>
